## 1.5.3 넘파이의 산술 연산

In [4]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x)
print(type(x))
print(x*y)
print(x+y)

[1. 2. 3.]
<class 'numpy.ndarray'>
[ 2.  8. 18.]
[3. 6. 9.]


## 1.5.4 넘파이의 N차원 배열

In [15]:
A = np.array([[1,2], [3,4]])
B = np.array([[3,0], [0,6]])
print("A : ", A)
print(A.shape)
print(A.dtype)
C = A+B
print("C : ", C)
D = A*B
print("D : ", D)
print("A*10 : ", A*10)

A :  [[1 2]
 [3 4]]
(2, 2)
int64
C :  [[ 4  2]
 [ 3 10]]
D :  [[ 3  0]
 [ 0 24]]
A*10 :  [[10 20]
 [30 40]]


## 1.5.5 브로드캐스트
행렬 곱셈

In [17]:
B = np.array([10,20])
print(A*B)

[[10 40]
 [30 80]]


## 1.5.6 원소 접근

In [29]:
X = np.array([[51,55], [14,19], [0,4]])
print("X : ", X)
print("X[0] :", X[0])
print("X[0][1]", X[0][1])

X_vector = X.flatten()  # X를 1차원 배열로 변환(평탄화)
print("X_vector : ",X_vector)
print(X_vector[np.array([0,2,4])])  # 인덱스가 0,2,4인 원소 얻기
print("X_vector > 15 : ", X_vector > 15)
print("X가 15이상인 값 : ", X_vector[X_vector>15])

X :  [[51 55]
 [14 19]
 [ 0  4]]
X[0] : [51 55]
X[0][1] 55
X_vector :  [51 55 14 19  0  4]
[51 14  0]
X_vector > 15 :  [ True  True False  True False False]
X가 15이상인 값 :  [51 55 19]
